"""Intent RL Dataset — 100 fragmented human thoughts with ground truth.

Each test case simulates how a real human would speak to MyndLens:
- Fragmented, incomplete sentences
- Pronouns without context
- Implied actions
- Casual/shorthand speech

Ground truth includes the intended action_class and a semantic description
that the L1 Scout should approximately match.
"""

INTENT_DATASET = [
    # ── COMM_SEND (15 cases) ─────────────────────────────────────────────
    {"id": 1, "fragment": "tell sarah about the thing tomorrow",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send a message to Sarah about an event/topic happening tomorrow"}},
    {"id": 2, "fragment": "shoot bob a quick email yeah the budget numbers",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send Bob an email about budget numbers"}},
    {"id": 3, "fragment": "can you text mike im running late",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send a text message to Mike saying I'm running late"}},
    {"id": 4, "fragment": "forward that report to the whole team",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Forward a report to the entire team"}},
    {"id": 5, "fragment": "reply to jess saying we're good for friday",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Reply to Jess confirming availability for Friday"}},
    {"id": 6, "fragment": "ping the devs on slack about the outage",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send a Slack message to developers about a system outage"}},
    {"id": 7, "fragment": "whatsapp mom happy birthday",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send a WhatsApp birthday message to mom"}},
    {"id": 8, "fragment": "let the client know we need another week",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Notify the client that an additional week is needed"}},
    {"id": 9, "fragment": "send the presentation slides to everyone who was in the meeting",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send presentation slides to all meeting attendees"}},
    {"id": 10, "fragment": "drop a note to HR about my leave next month",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send a message to HR about upcoming leave next month"}},
    {"id": 11, "fragment": "notify accounting the invoices are approved",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Notify accounting department that invoices are approved"}},
    {"id": 12, "fragment": "message the landlord about the broken heater",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send a message to the landlord about a broken heater"}},
    {"id": 13, "fragment": "tell my boss I finished the quarterly review",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Inform boss that the quarterly review is completed"}},
    {"id": 14, "fragment": "email the vendor asking for a revised quote",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Email the vendor requesting a revised price quote"}},
    {"id": 15, "fragment": "send john the meeting notes from yesterday",
     "ground_truth": {"intent_category": "COMM_SEND", "intent": "Send yesterday's meeting notes to John"}},

    # ── SCHED_MODIFY (12 cases) ──────────────────────────────────────────
    {"id": 16, "fragment": "move my 3pm to tomorrow same time",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Reschedule the 3pm meeting to tomorrow at the same time"}},
    {"id": 17, "fragment": "book a room for the standup on thursday",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Book a meeting room for the Thursday standup"}},
    {"id": 18, "fragment": "cancel the dentist appointment",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Cancel the dentist appointment"}},
    {"id": 19, "fragment": "set up a call with the investors next week",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Schedule a call with investors for next week"}},
    {"id": 20, "fragment": "push the sprint review to after lunch",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Reschedule the sprint review to the afternoon"}},
    {"id": 21, "fragment": "block off friday afternoon for deep work",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Block Friday afternoon on the calendar for focused work"}},
    {"id": 22, "fragment": "add a recurring 1-on-1 with lisa every monday at 10",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Create a recurring weekly 1-on-1 meeting with Lisa on Mondays at 10am"}},
    {"id": 23, "fragment": "reschedule the whole week i'm out sick",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Reschedule all meetings for the week due to being sick"}},
    {"id": 24, "fragment": "find a time that works for me and sarah and bob this week",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Find a mutually available time slot for a meeting with Sarah and Bob this week"}},
    {"id": 25, "fragment": "extend the team meeting by 30 minutes",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Extend the duration of the team meeting by 30 minutes"}},
    {"id": 26, "fragment": "make the wednesday sync biweekly instead",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Change the Wednesday sync meeting from weekly to biweekly"}},
    {"id": 27, "fragment": "schedule lunch with alex at the italian place",
     "ground_truth": {"intent_category": "SCHED_MODIFY", "intent": "Schedule a lunch meeting with Alex at an Italian restaurant"}},

    # ── INFO_RETRIEVE (15 cases) ─────────────────────────────────────────
    {"id": 28, "fragment": "what was the revenue last quarter",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve last quarter's revenue figures"}},
    {"id": 29, "fragment": "check if the PR got merged",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Check the status of a pull request merge"}},
    {"id": 30, "fragment": "who's the contact at that design agency",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Look up the contact person at a design agency"}},
    {"id": 31, "fragment": "what's the status of the johnson proposal",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Check the status of the Johnson proposal"}},
    {"id": 32, "fragment": "look up flights to tokyo in march",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Search for flights to Tokyo in March"}},
    {"id": 33, "fragment": "how many open tickets do we have",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve the count of open support tickets"}},
    {"id": 34, "fragment": "find out when the lease expires",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Look up the lease expiration date"}},
    {"id": 35, "fragment": "what did sarah say about the timeline",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve Sarah's comments about a project timeline"}},
    {"id": 36, "fragment": "get me the latest exchange rate for euros",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Look up the current EUR exchange rate"}},
    {"id": 37, "fragment": "show me the weather for this weekend",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve the weekend weather forecast"}},
    {"id": 38, "fragment": "when does the gym close today",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Find today's gym closing time"}},
    {"id": 39, "fragment": "whats trending on twitter right now",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve current trending topics on Twitter"}},
    {"id": 40, "fragment": "pull up the contract we signed with acme",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve the signed contract with Acme"}},
    {"id": 41, "fragment": "what's our churn rate this month",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Retrieve this month's customer churn rate"}},
    {"id": 42, "fragment": "find the recipe for that pasta thing we made last week",
     "ground_truth": {"intent_category": "INFO_RETRIEVE", "intent": "Search for a pasta recipe made recently"}},

    # ── DOC_EDIT (10 cases) ───────────────────────────────────────────────
    {"id": 43, "fragment": "draft an apology email to the customer about the delay",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Draft an apology email to a customer regarding a delivery delay"}},
    {"id": 44, "fragment": "write up the meeting notes from today's standup",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Create meeting notes from today's standup meeting"}},
    {"id": 45, "fragment": "update the project readme with the new endpoints",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Update the project README file with new API endpoints"}},
    {"id": 46, "fragment": "create a summary of the research paper on climate change",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Create a summary document of a climate change research paper"}},
    {"id": 47, "fragment": "put together a proposal for the new feature",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Create a feature proposal document"}},
    {"id": 48, "fragment": "edit the blog post to fix the typos",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Edit a blog post to correct typos"}},
    {"id": 49, "fragment": "make a linkedin post about our latest product launch",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Create a LinkedIn post about a product launch"}},
    {"id": 50, "fragment": "help me write a cover letter for the PM role",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Draft a cover letter for a Product Manager position"}},
    {"id": 51, "fragment": "rewrite the terms of service to be more user friendly",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Rewrite the terms of service document in simpler language"}},
    {"id": 52, "fragment": "compile the weekly status report from everyones updates",
     "ground_truth": {"intent_category": "DOC_EDIT", "intent": "Compile a weekly status report from team updates"}},

    # ── CODE_GEN (8 cases) ────────────────────────────────────────────────
    {"id": 53, "fragment": "write a python script to rename all the files in that folder",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Write a Python script to batch rename files in a directory"}},
    {"id": 54, "fragment": "build me a quick dashboard for the sales data",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Build a dashboard to visualize sales data"}},
    {"id": 55, "fragment": "fix the login bug where users cant reset passwords",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Fix a bug in the login system's password reset flow"}},
    {"id": 56, "fragment": "create a sql query to find duplicate customers",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Write a SQL query to identify duplicate customer records"}},
    {"id": 57, "fragment": "add input validation to the signup form",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Add input validation logic to the signup form"}},
    {"id": 58, "fragment": "make an api endpoint for user profiles",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Create a REST API endpoint for user profile management"}},
    {"id": 59, "fragment": "write a regex to match email addresses",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Write a regex pattern to validate email addresses"}},
    {"id": 60, "fragment": "refactor the payment module to use stripe",
     "ground_truth": {"intent_category": "CODE_GEN", "intent": "Refactor the payment module to integrate with Stripe"}},

    # ── FIN_TRANS (10 cases) ──────────────────────────────────────────────
    {"id": 61, "fragment": "pay the electricity bill",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Pay the electricity bill"}},
    {"id": 62, "fragment": "send an invoice to the client for the consulting work",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Create and send an invoice to the client for consulting services"}},
    {"id": 63, "fragment": "request a refund for the duplicate charge",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Request a refund for a duplicate charge"}},
    {"id": 64, "fragment": "log the uber ride as a business expense",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Log an Uber ride as a business expense"}},
    {"id": 65, "fragment": "transfer 500 to savings",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Transfer 500 currency units to savings account"}},
    {"id": 66, "fragment": "get a quote from three different suppliers",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Request price quotes from three different suppliers"}},
    {"id": 67, "fragment": "cancel the netflix subscription",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Cancel the Netflix subscription"}},
    {"id": 68, "fragment": "split the dinner bill with alex and mike",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Split a dinner bill between Alex and Mike"}},
    {"id": 69, "fragment": "check if the vendor payment went through",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Verify if a vendor payment was successfully processed"}},
    {"id": 70, "fragment": "set up autopay for rent",
     "ground_truth": {"intent_category": "FIN_TRANS", "intent": "Set up automatic payment for rent"}},

    # ── TASK_CREATE (8 cases) ─────────────────────────────────────────────
    {"id": 71, "fragment": "add buy groceries to my to do list",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Add 'buy groceries' to the to-do list"}},
    {"id": 72, "fragment": "i need to follow up with the lead from the conference",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Create a follow-up task for a conference lead"}},
    {"id": 73, "fragment": "put review the contract on my plate for tomorrow",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Add 'review contract' as a task for tomorrow"}},
    {"id": 74, "fragment": "make a note to renew the domain before it expires",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Create a task to renew the domain name before expiry"}},
    {"id": 75, "fragment": "track that i owe lisa 50 bucks",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Create a note tracking a 50 dollar debt to Lisa"}},
    {"id": 76, "fragment": "add prepare demo to the sprint backlog",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Add 'prepare demo' to the sprint backlog"}},
    {"id": 77, "fragment": "i should really clean up the garage this weekend",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Create a task to clean the garage this weekend"}},
    {"id": 78, "fragment": "we need to onboard the new hire by monday",
     "ground_truth": {"intent_category": "TASK_CREATE", "intent": "Create an onboarding task for a new hire due Monday"}},

    # ── REMINDER_SET (7 cases) ────────────────────────────────────────────
    {"id": 79, "fragment": "remind me to call the doctor at 2pm",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set a reminder to call the doctor at 2pm"}},
    {"id": 80, "fragment": "dont let me forget sarahs birthday next tuesday",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set a reminder for Sarah's birthday next Tuesday"}},
    {"id": 81, "fragment": "buzz me when the meeting is about to start",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set a reminder before the meeting starts"}},
    {"id": 82, "fragment": "remind me to take the medicine after dinner",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set a reminder to take medicine after dinner"}},
    {"id": 83, "fragment": "alert me if bitcoin drops below 40k",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set a price alert for Bitcoin below 40,000"}},
    {"id": 84, "fragment": "wake me up at 6am sharp",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set an alarm for 6am"}},
    {"id": 85, "fragment": "remind me in 30 minutes to check the oven",
     "ground_truth": {"intent_category": "REMINDER_SET", "intent": "Set a 30-minute reminder to check the oven"}},

    # ── DATA_ANALYZE (10 cases) ───────────────────────────────────────────
    {"id": 86, "fragment": "compare our sales this quarter vs last quarter",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Compare quarterly sales data"}},
    {"id": 87, "fragment": "chart the website traffic for the past 6 months",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Create a chart of website traffic over 6 months"}},
    {"id": 88, "fragment": "what's the trend in customer complaints",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Analyze the trend in customer complaints"}},
    {"id": 89, "fragment": "break down where our marketing budget went",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Analyze marketing budget allocation breakdown"}},
    {"id": 90, "fragment": "run a sentiment analysis on the product reviews",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Perform sentiment analysis on product reviews"}},
    {"id": 91, "fragment": "calculate the roi on the ad campaign",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Calculate the ROI of an advertising campaign"}},
    {"id": 92, "fragment": "find patterns in the support ticket data",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Identify patterns in support ticket data"}},
    {"id": 93, "fragment": "forecast next months revenue based on current trends",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Forecast next month's revenue from current data trends"}},
    {"id": 94, "fragment": "what percentage of users complete onboarding",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Calculate the onboarding completion rate"}},
    {"id": 95, "fragment": "correlate weather data with ice cream sales",
     "ground_truth": {"intent_category": "DATA_ANALYZE", "intent": "Analyze correlation between weather and ice cream sales"}},

    # ── AUTOMATION (5 cases) ──────────────────────────────────────────────
    {"id": 96, "fragment": "every time a new lead comes in send me a summary",
     "ground_truth": {"intent_category": "AUTOMATION", "intent": "Create an automation to send lead summaries on new lead events"}},
    {"id": 97, "fragment": "automatically archive emails older than 90 days",
     "ground_truth": {"intent_category": "AUTOMATION", "intent": "Set up automatic email archiving after 90 days"}},
    {"id": 98, "fragment": "whenever someone mentions us on twitter notify the team",
     "ground_truth": {"intent_category": "AUTOMATION", "intent": "Create a Twitter mention notification automation for the team"}},
    {"id": 99, "fragment": "if the server goes down page the on-call engineer",
     "ground_truth": {"intent_category": "AUTOMATION", "intent": "Set up automatic paging for on-call engineer on server downtime"}},
    {"id": 100, "fragment": "sync my calendar events to the shared team spreadsheet daily",
     "ground_truth": {"intent_category": "AUTOMATION", "intent": "Create a daily automation to sync calendar events to a team spreadsheet"}},
]

# All action classes used
INTENT_CATEGORIES = sorted(set(d["ground_truth"]["intent_category"] for d in INTENT_DATASET))
